complexity:
  CyclomaticComplexMethod:
    threshold: 25
formatting:
  MaximumLineLength:
    maxLineLength: 140
  ParameterListWrapping:
    maxLineLength: 140
style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
